version: "3.9"

services:
  fastapi:
    build:
      context: .
    ports:
      - "8000:8000"
    command: uvicorn src.fastapi_app:app --host 0.0.0.0 --port 8000 --reload

  streamlit:
    build:
      context: .
    ports:
      - "8501:8501"
    command: streamlit run streamlit_app/home_page.py --server.port 8501 --server.address 0.0.0.0